# Generated by Django 4.0.4 on 2022-04-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
