# Generated by Django 4.0.4 on 2022-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
