# Generated by Django 4.0.4 on 2022-04-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
